import type { Question } from '../types'

/**
 * Third first-party question pack (original, MIT): "Origins, accidents &
 * 'originally called'." Same fill-in-the-blank format as QUESTION_POOL —
 * short, fakeable answers, a visible blank, and forbidden guesses for the
 * too-obvious / joke picks. Every fact here was verified against an
 * authoritative source (encyclopedias, museums, the brand's own history,
 * Smithsonian, Snopes/JSTOR for myth-busting) before shipping; debunked
 * "fun facts" (Coca-Cola was green, the Crum potato-chip legend, the Eiffel
 * Tower was meant for Barcelona) were deliberately left out.
 */
export const FUN_ORIGINS_QUESTIONS: Question[] = [
  // --- Originally called: tech & brands ---
  {
    id: 'b3-google-backrub',
    category: 'Origins',
    difficulty: 'medium',
    prompt: 'Before they settled on the name we know, the two Stanford students behind Google ran their search engine under the name ___.',
    answer: 'BackRub',
    acceptableAnswers: ['Back Rub', 'Backrub'],
    forbiddenAnswers: ['Google', 'Googol', 'Yahoo'],
  },
  {
    id: 'b3-amazon-cadabra',
    category: 'Origins',
    difficulty: 'hard',
    prompt: 'Jeff Bezos first registered his online store under a magic-word name, ___, before a lawyer kept mishearing it as "cadaver."',
    answer: 'Cadabra',
    acceptableAnswers: ['Cadabra.com'],
    forbiddenAnswers: ['Amazon', 'Abracadabra', 'Relentless'],
  },
  {
    id: 'b3-twitter-twttr',
    category: 'Origins',
    difficulty: 'medium',
    prompt: 'Inspired by Flickr, the team built their messaging service under the vowel-less working name ___ before buying the full domain.',
    answer: 'Twttr',
    acceptableAnswers: ['twttr'],
    forbiddenAnswers: ['Twitter', 'Tweeter', 'X'],
  },
  {
    id: 'b3-nike-brs',
    category: 'Origins',
    difficulty: 'hard',
    prompt: 'For its first seven years the sportswear giant Nike operated under the much plainer name ___ Sports.',
    answer: 'Blue Ribbon',
    acceptableAnswers: ['Blue Ribbon Sports', 'BRS'],
    forbiddenAnswers: ['Nike', 'Onitsuka', 'Swoosh'],
  },
  {
    id: 'b3-pepsi-brads',
    category: 'Origins',
    difficulty: 'medium',
    prompt: 'When a North Carolina pharmacist first mixed it up in 1893, the soda we call Pepsi was sold simply as "___’s Drink."',
    answer: 'Brad',
    acceptableAnswers: ["Brad's", 'Brads', "Brad's Drink"],
    forbiddenAnswers: ['Pepsi', 'Caleb', 'Cola'],
  },
  {
    id: 'b3-nintendo-cards',
    category: 'Origins',
    difficulty: 'medium',
    prompt: 'Decades before video games, the company Nintendo got its start in 1889 making ___.',
    answer: 'playing cards',
    acceptableAnswers: ['cards', 'hanafuda', 'hanafuda cards'],
    forbiddenAnswers: ['video games', 'consoles', 'toys'],
  },

  // --- Named after a person or place ---
  {
    id: 'b3-frisbee-pie',
    category: 'Origins',
    difficulty: 'medium',
    prompt: 'The flying disc called the Frisbee took its name from a Connecticut company that sold ___. Students used to toss the empty tins.',
    answer: 'pies',
    acceptableAnswers: ['pie', 'pies', 'pie tins'],
    forbiddenAnswers: ['discs', 'frisbees', 'cookies'],
  },
  {
    id: 'b3-saxophone-sax',
    category: 'Origins',
    difficulty: 'medium',
    prompt: 'The saxophone is named after the Belgian instrument-maker who invented it in the 1840s, Adolphe ___.',
    answer: 'Sax',
    acceptableAnswers: ['Sax', 'Saxe'],
    forbiddenAnswers: ['Saxophone', 'Phone', 'Selmer'],
  },
  {
    id: 'b3-ferris-ferris',
    category: 'Origins',
    difficulty: 'hard',
    prompt: 'The giant amusement-park wheel debuted at the 1893 Chicago World’s Fair and is named after its engineer, George ___.',
    answer: 'Ferris',
    acceptableAnswers: ['Ferris'],
    forbiddenAnswers: ['Eiffel', 'Wheeler', 'Chicago'],
  },
  {
    id: 'b3-cocacola-kola',
    category: 'Origins',
    difficulty: 'hard',
    prompt: 'Coca-Cola was named for two of its original ingredients: the coca leaf and the caffeine-rich ___ nut.',
    answer: 'kola',
    acceptableAnswers: ['kola', 'cola'],
    forbiddenAnswers: ['cocoa', 'coca', 'pecan'],
  },
  {
    id: 'b3-brandy-burnt',
    category: 'Origins',
    difficulty: 'hard',
    prompt: 'The word "brandy" comes from a Dutch term that literally translates to "burnt ___."',
    answer: 'wine',
    acceptableAnswers: ['wine'],
    forbiddenAnswers: ['water', 'grapes', 'sugar'],
  },
  {
    id: 'b3-wd40-attempts',
    category: 'Origins',
    difficulty: 'hard',
    prompt: 'The lubricant WD-40 is named for "Water Displacement" and the number of the lab attempt that finally worked: the ___th.',
    answer: '40',
    acceptableAnswers: ['40', 'fortieth', '40th'],
    forbiddenAnswers: ['1', '4', '100'],
  },

  // --- Invented by accident ---
  {
    id: 'b3-microwave-radar',
    category: 'Origins',
    difficulty: 'medium',
    prompt: 'An engineer invented the microwave oven after a chocolate bar melted in his pocket while he was working on ___ equipment.',
    answer: 'radar',
    acceptableAnswers: ['radar', 'a radar'],
    forbiddenAnswers: ['heating', 'an oven', 'a stove'],
  },
  {
    id: 'b3-penicillin-mold',
    category: 'Origins',
    difficulty: 'medium',
    prompt: 'Alexander Fleming discovered the first antibiotic, penicillin, by accident when ___ contaminated a dish he’d left out.',
    answer: 'mold',
    acceptableAnswers: ['mould', 'a mold', 'fungus'],
    forbiddenAnswers: ['bacteria', 'a virus', 'dust'],
  },
  {
    id: 'b3-postit-glue',
    category: 'Origins',
    difficulty: 'hard',
    prompt: 'Post-it Notes exist because a 3M chemist trying to make a super-strong glue accidentally made one that was unusually ___ instead.',
    answer: 'weak',
    acceptableAnswers: ['weak', 'weak adhesive', 'low-tack'],
    forbiddenAnswers: ['strong', 'sticky', 'yellow'],
  },
  {
    id: 'b3-superglue-sights',
    category: 'Origins',
    difficulty: 'hard',
    prompt: 'Super Glue was discovered during World War II by a chemist who was actually trying to make clear plastic gun ___.',
    answer: 'sights',
    acceptableAnswers: ['sights', 'gun sights'],
    forbiddenAnswers: ['barrels', 'triggers', 'handles'],
  },
  {
    id: 'b3-teflon-refrigerant',
    category: 'Origins',
    difficulty: 'hard',
    prompt: 'The slippery non-stick coating Teflon was discovered by accident by a chemist trying to invent a new ___.',
    answer: 'refrigerant',
    acceptableAnswers: ['refrigerant', 'coolant', 'refrigerant gas'],
    forbiddenAnswers: ['plastic', 'paint', 'glue'],
  },
  {
    id: 'b3-bubblewrap-wallpaper',
    category: 'Origins',
    difficulty: 'hard',
    prompt: 'Two engineers first tried to sell Bubble Wrap in the 1950s as textured ___ before anyone thought of using it for packaging.',
    answer: 'wallpaper',
    acceptableAnswers: ['wall paper'],
    forbiddenAnswers: ['packaging', 'insulation', 'flooring'],
  },
  {
    id: 'b3-slinky-springs',
    category: 'Origins',
    difficulty: 'hard',
    prompt: 'The toy Slinky was discovered when a naval engineer knocked a ___ off a shelf and watched it "walk" across the floor.',
    answer: 'spring',
    acceptableAnswers: ['spring', 'a spring', 'coil'],
    forbiddenAnswers: ['slinky', 'wire', 'ball'],
  },

  // --- Originally sold / used as something else ---
  {
    id: 'b3-playdoh-cleaner',
    category: 'Origins',
    difficulty: 'medium',
    prompt: 'Before it became a kids’ modeling toy, Play-Doh was sold as a product to clean ___.',
    answer: 'wallpaper',
    acceptableAnswers: ['wall paper', 'walls'],
    forbiddenAnswers: ['hands', 'floors', 'teeth'],
  },
  {
    id: 'b3-listerine-antiseptic',
    category: 'Origins',
    difficulty: 'hard',
    prompt: 'Long before it was a mouthwash, Listerine was first marketed in the 1880s as a surgical ___.',
    answer: 'antiseptic',
    acceptableAnswers: ['antiseptic', 'disinfectant'],
    forbiddenAnswers: ['mouthwash', 'soap', 'perfume'],
  },
  {
    id: 'b3-kleenex-makeup',
    category: 'Origins',
    difficulty: 'hard',
    prompt: 'Kleenex tissues were first sold in the 1920s as a way to wipe off cold cream and ___.',
    answer: 'makeup',
    acceptableAnswers: ['makeup', 'make-up', 'make up', 'cosmetics'],
    forbiddenAnswers: ['noses', 'tears', 'sweat'],
  },
  {
    id: 'b3-vaseline-oilrigs',
    category: 'Origins',
    difficulty: 'hard',
    prompt: 'A chemist created Vaseline after noticing workers smear a gooey residue from ___ machinery on their cuts and burns.',
    answer: 'oil rig',
    acceptableAnswers: ['oil rig', 'oil rigs', 'oil drilling', 'oil well', 'oil wells'],
    forbiddenAnswers: ['kitchen', 'car', 'factory'],
  },
  {
    id: 'b3-viagra-heart',
    category: 'Origins',
    difficulty: 'medium',
    prompt: 'The drug now known as Viagra was originally tested as a treatment for chest pain and ___ disease.',
    answer: 'heart',
    acceptableAnswers: ['heart', 'the heart'],
    forbiddenAnswers: ['lung', 'brain', 'kidney'],
  },
  {
    id: 'b3-7up-lithium',
    category: 'Origins',
    difficulty: 'hard',
    prompt: 'Until 1948 the lemon-lime soda 7 Up contained ___ citrate, a compound now used as a mood stabilizer.',
    answer: 'lithium',
    acceptableAnswers: ['lithium', 'lithium citrate'],
    forbiddenAnswers: ['caffeine', 'sugar', 'cocaine'],
  },
  {
    id: 'b3-graham-health',
    category: 'Origins',
    difficulty: 'hard',
    prompt: 'The graham cracker was invented in the 1800s by a clergyman who pushed it as a bland ___ food.',
    answer: 'health',
    acceptableAnswers: ['health', 'diet', 'health-food'],
    forbiddenAnswers: ['dessert', 'campfire', 'baby'],
  },
  {
    id: 'b3-tonic-malaria',
    category: 'Origins',
    difficulty: 'hard',
    prompt: 'The quinine in tonic water was originally taken as a medicine to fight ___; gin was added just to mask the bitterness.',
    answer: 'malaria',
    acceptableAnswers: ['malaria'],
    forbiddenAnswers: ['scurvy', 'a cold', 'a hangover'],
  },
  {
    id: 'b3-pringles-potato',
    category: 'Origins',
    difficulty: 'hard',
    prompt: 'To win a UK tax case, Pringles’ maker argued they aren’t really potato chips because they’re only about ___ percent potato.',
    answer: '42',
    acceptableAnswers: ['42', 'forty-two', '40'],
    forbiddenAnswers: ['100', '90', '10'],
  },
]
