import type { Question } from '../types'

/**
 * Records, places & history oddities pack (original, MIT). Same fill-in-the-blank
 * format as QUESTION_POOL: a surprising, well-documented "huh, really?!" fact with
 * a short, fakeable answer, a visible blank, and forbidden guesses for the
 * too-obvious / joke picks. Every fact here was checked against an authoritative
 * source (Wikipedia, Guinness World Records, Britannica, NASA, UNESCO, OHCHR,
 * official site, etc.) before shipping. Records change — re-verify before edits.
 */
export const FUN_RECORDS_QUESTIONS: Question[] = [
  // --- Geography people get wrong ---
  {
    id: 'b5-turkey-capital',
    category: 'Geography',
    difficulty: 'medium',
    prompt: 'Turkey’s capital is ___, even though Istanbul is nearly three times bigger.',
    answer: 'Ankara',
    acceptableAnswers: [],
    forbiddenAnswers: ['Istanbul', 'Turkey', 'Constantinople'],
  },
  {
    id: 'b5-brazil-capital',
    category: 'Geography',
    difficulty: 'medium',
    prompt: 'Brazil’s capital is the purpose-built city of ___, not its largest city São Paulo or famous Rio.',
    answer: 'Brasília',
    acceptableAnswers: ['Brasilia'],
    forbiddenAnswers: ['Rio de Janeiro', 'São Paulo', 'Brazil'],
  },
  {
    id: 'b5-sa-legislative-capital',
    category: 'Geography',
    difficulty: 'hard',
    prompt: 'South Africa has three capitals; the one where Parliament actually sits is ___.',
    answer: 'Cape Town',
    acceptableAnswers: [],
    forbiddenAnswers: ['Johannesburg', 'Pretoria', 'Durban'],
  },
  {
    id: 'b5-northernmost-capital',
    category: 'Geography',
    difficulty: 'hard',
    prompt: 'The northernmost capital city of any sovereign country is ___.',
    answer: 'Reykjavík',
    acceptableAnswers: ['Reykjavik'],
    forbiddenAnswers: ['Oslo', 'Helsinki', 'Moscow'],
  },
  {
    id: 'b5-southernmost-capital',
    category: 'Geography',
    difficulty: 'hard',
    prompt: 'The southernmost capital city of any sovereign country is ___, in New Zealand.',
    answer: 'Wellington',
    acceptableAnswers: [],
    forbiddenAnswers: ['Auckland', 'Canberra', 'Sydney'],
  },
  {
    id: 'b5-most-time-zones',
    category: 'Geography',
    difficulty: 'hard',
    prompt: 'Thanks to its scattered overseas territories, the country spanning the most time zones (12) is ___, not Russia or the USA.',
    answer: 'France',
    acceptableAnswers: [],
    forbiddenAnswers: ['Russia', 'United States', 'USA'],
  },
  {
    id: 'b5-most-borders',
    category: 'Geography',
    difficulty: 'hard',
    prompt: 'Tied with China for the most neighbouring countries, this nation shares a land border with 14 of them: ___.',
    answer: 'Russia',
    acceptableAnswers: [],
    forbiddenAnswers: ['China', 'Germany', 'Brazil'],
  },
  {
    id: 'b5-no-river',
    category: 'Geography',
    difficulty: 'hard',
    prompt: 'The largest country on Earth with no permanent natural river at all is ___.',
    answer: 'Saudi Arabia',
    acceptableAnswers: [],
    forbiddenAnswers: ['Egypt', 'Australia', 'Antarctica'],
  },
  {
    id: 'b5-canada-lakes',
    category: 'Geography',
    difficulty: 'medium',
    prompt: 'The country that has more lakes than any other on Earth, well over half a million, is ___.',
    answer: 'Canada',
    acceptableAnswers: [],
    forbiddenAnswers: ['Russia', 'Finland', 'USA'],
  },
  {
    id: 'b5-deepest-lake',
    category: 'Geography',
    difficulty: 'hard',
    prompt: 'The deepest lake in the world, holding about a fifth of all the planet’s unfrozen fresh water, is Lake ___ in Siberia.',
    answer: 'Baikal',
    acceptableAnswers: ['Lake Baikal'],
    forbiddenAnswers: ['Superior', 'Victoria', 'Tahoe'],
  },
  {
    id: 'b5-tallest-waterfall',
    category: 'Geography',
    difficulty: 'medium',
    prompt: 'The tallest waterfall on Earth, plunging nearly a kilometre off a flat-topped mountain, is ___ Falls in Venezuela.',
    answer: 'Angel',
    acceptableAnswers: ['Angel Falls', 'Salto Ángel'],
    forbiddenAnswers: ['Niagara', 'Victoria', 'Iguazu'],
  },
  {
    id: 'b5-longest-placename',
    category: 'Geography',
    difficulty: 'hard',
    prompt: 'The 85-letter Taumatawhakatangihanga… hill, holding the record for longest single-word place name, is in the country of ___.',
    answer: 'New Zealand',
    acceptableAnswers: [],
    forbiddenAnswers: ['Wales', 'Iceland', 'Australia'],
  },
  {
    id: 'b5-diomede',
    category: 'Geography',
    difficulty: 'hard',
    prompt: 'Across the Bering Strait, the USA and this country sit only about 2.4 miles apart at the Diomede Islands: ___.',
    answer: 'Russia',
    acceptableAnswers: [],
    forbiddenAnswers: ['Canada', 'Japan', 'Alaska'],
  },

  // --- World records & superlatives ---
  {
    id: 'b5-shortest-war',
    category: 'History',
    difficulty: 'hard',
    prompt: 'The shortest war in recorded history, the 1896 Anglo-Zanzibar War, lasted roughly this many minutes: ___.',
    answer: '38',
    acceptableAnswers: ['thirty-eight', '38 minutes', 'about 40'],
    forbiddenAnswers: ['1', '500', 'a year'],
  },
  {
    id: 'b5-hottest-pepper',
    category: 'Food',
    difficulty: 'medium',
    prompt: 'The current Guinness record holder for the world’s hottest chili pepper is named Pepper ___.',
    answer: 'X',
    acceptableAnswers: ['Pepper X'],
    forbiddenAnswers: ['Carolina Reaper', 'Ghost', 'Z'],
  },
  {
    id: 'b5-most-translated',
    category: 'History',
    difficulty: 'hard',
    prompt: 'The most translated document in the world, available in over 500 languages, is the Universal Declaration of Human ___.',
    answer: 'Rights',
    acceptableAnswers: [],
    forbiddenAnswers: ['Dignity', 'Freedom', 'Peace'],
  },
  {
    id: 'b5-vatican-wine',
    category: 'Geography',
    difficulty: 'hard',
    prompt: 'Driven by tiny population and daily Mass, the place that drinks the most wine per person on Earth is ___ City.',
    answer: 'Vatican',
    acceptableAnswers: ['the Vatican', 'Vatican City'],
    forbiddenAnswers: ['France', 'Italy', 'Napa'],
  },
  {
    id: 'b5-oldest-tree',
    category: 'History',
    difficulty: 'hard',
    prompt: 'The oldest known single living tree, a bristlecone pine over 4,800 years old in California, is nicknamed ___.',
    answer: 'Methuselah',
    acceptableAnswers: [],
    forbiddenAnswers: ['Goliath', 'Yggdrasil', 'Methusela'],
  },
  {
    id: 'b5-tallest-mountain-ss',
    category: 'Space',
    difficulty: 'hard',
    prompt: 'The tallest mountain in the entire solar system, about two and a half times the height of Everest, is Olympus Mons on the planet ___.',
    answer: 'Mars',
    acceptableAnswers: [],
    forbiddenAnswers: ['Jupiter', 'Venus', 'the Moon'],
  },

  // --- Bizarre-but-true history ---
  {
    id: 'b5-oldest-company',
    category: 'History',
    difficulty: 'hard',
    prompt: 'The world’s oldest continuously operating company, a temple-building firm founded in the year 578, is based in the country of ___.',
    answer: 'Japan',
    acceptableAnswers: [],
    forbiddenAnswers: ['China', 'Italy', 'Egypt'],
  },
  {
    id: 'b5-oxford-aztec',
    category: 'History',
    difficulty: 'hard',
    prompt: 'Oxford had been teaching for over 200 years before the Aztecs even founded their capital city of ___ in 1325.',
    answer: 'Tenochtitlan',
    acceptableAnswers: ['Tenochtitlán'],
    forbiddenAnswers: ['Mexico City', 'Machu Picchu', 'Cusco'],
  },
  {
    id: 'b5-cleopatra-pyramid',
    category: 'History',
    difficulty: 'hard',
    prompt: 'Cleopatra lived closer in time to the first Moon landing than to the building of the Great ___ of Giza.',
    answer: 'Pyramid',
    acceptableAnswers: ['Pyramids'],
    forbiddenAnswers: ['Sphinx', 'Wall', 'Temple'],
  },
  {
    id: 'b5-fax-vs-phone',
    category: 'History',
    difficulty: 'hard',
    prompt: 'Patented in 1843, more than 30 years before the telephone, the surprisingly old invention is the ___ machine.',
    answer: 'fax',
    acceptableAnswers: ['fax machine', 'facsimile'],
    forbiddenAnswers: ['washing', 'sewing', 'time'],
  },
  {
    id: 'b5-nintendo',
    category: 'History',
    difficulty: 'medium',
    prompt: 'Founded back in 1889, the company Nintendo originally made hand-painted ___ before video games existed.',
    answer: 'playing cards',
    acceptableAnswers: ['cards', 'hanafuda', 'hanafuda cards'],
    forbiddenAnswers: ['toys', 'consoles', 'noodles'],
  },
  {
    id: 'b5-last-slavery',
    category: 'History',
    difficulty: 'hard',
    prompt: 'The last country in the world to officially abolish slavery, only doing so in 1981, was ___.',
    answer: 'Mauritania',
    acceptableAnswers: [],
    forbiddenAnswers: ['United States', 'Brazil', 'Sudan'],
  },
  {
    id: 'b5-ebay-first',
    category: 'History',
    difficulty: 'medium',
    prompt: 'The very first item ever sold on eBay, in 1995, was a broken ___.',
    answer: 'laser pointer',
    acceptableAnswers: ['laser pen', 'laser'],
    forbiddenAnswers: ['phone', 'computer', 'car'],
  },
  {
    id: 'b5-first-barcode',
    category: 'History',
    difficulty: 'hard',
    prompt: 'The first product ever scanned by a checkout barcode, in 1974, was a pack of Wrigley’s ___.',
    answer: 'chewing gum',
    acceptableAnswers: ['gum', 'Juicy Fruit', 'chewing gum (Juicy Fruit)'],
    forbiddenAnswers: ['cigarettes', 'soda', 'milk'],
  },

  // --- Space / measurement oddities ---
  {
    id: 'b5-venus-day',
    category: 'Space',
    difficulty: 'hard',
    prompt: 'The one planet in our solar system where a single day lasts longer than its entire year is ___.',
    answer: 'Venus',
    acceptableAnswers: [],
    forbiddenAnswers: ['Mercury', 'Mars', 'Pluto'],
  },
]
