import type { Question } from '../types'

/**
 * "Weird-but-true" question pack (original, MIT). Surprising, well-documented
 * facts about animals, the human body, nature, and the origins of words —
 * each with a short, fakeable answer that's hard to guess but easy to invent
 * funny alternatives for. Every fact here was checked against an authoritative
 * source before shipping. Same fill-in-the-blank shape as QUESTION_POOL.
 */
export const FUN_WEIRD_QUESTIONS: Question[] = [
  // --- Collective nouns (great for funny lies) ---
  {
    id: 'b4-flamingos',
    category: 'Animals',
    difficulty: 'hard',
    prompt: 'The whimsical collective noun for a group of flamingos is a ___.',
    answer: 'flamboyance',
    acceptableAnswers: ['flamboyance of flamingos'],
    forbiddenAnswers: ['flock', 'flamingle', 'herd'],
  },
  {
    id: 'b4-owls',
    category: 'Animals',
    difficulty: 'medium',
    prompt: 'Because of their reputation for wisdom, a group of owls is traditionally called a ___.',
    answer: 'parliament',
    acceptableAnswers: ['parliament of owls'],
    forbiddenAnswers: ['flock', 'hoot', 'congress'],
  },
  {
    id: 'b4-jellyfish',
    category: 'Animals',
    difficulty: 'hard',
    prompt: 'A group of jellyfish drifting together is, fittingly, called a ___.',
    answer: 'smack',
    acceptableAnswers: ['smack of jellyfish'],
    forbiddenAnswers: ['school', 'sting', 'swarm'],
  },
  {
    id: 'b4-rhinos',
    category: 'Animals',
    difficulty: 'hard',
    prompt: 'The collective noun for a group of rhinoceroses is a ___.',
    answer: 'crash',
    acceptableAnswers: ['crash of rhinos', 'crash of rhinoceroses'],
    forbiddenAnswers: ['herd', 'charge', 'stampede'],
  },
  {
    id: 'b4-porcupines',
    category: 'Animals',
    difficulty: 'hard',
    prompt: 'A group of porcupines shares its name with the spiky feeling you get from their quills. It is called a ___.',
    answer: 'prickle',
    acceptableAnswers: ['prickle of porcupines'],
    forbiddenAnswers: ['herd', 'poke', 'pack'],
  },
  {
    id: 'b4-ferrets',
    category: 'Animals',
    difficulty: 'hard',
    prompt: 'A group of busy, scurrying ferrets is called a ___.',
    answer: 'business',
    acceptableAnswers: ['business of ferrets'],
    forbiddenAnswers: ['pack', 'fuzzle', 'litter'],
  },
  {
    id: 'b4-giraffes',
    category: 'Animals',
    difficulty: 'medium',
    prompt: 'Reflecting their towering height, a group of giraffes is commonly called a ___.',
    answer: 'tower',
    acceptableAnswers: ['tower of giraffes'],
    forbiddenAnswers: ['herd', 'stretch', 'flock'],
  },
  {
    id: 'b4-pandas',
    category: 'Animals',
    difficulty: 'hard',
    prompt: 'The unexpectedly self-conscious collective noun for a group of pandas is an ___.',
    answer: 'embarrassment',
    acceptableAnswers: ['embarrassment of pandas'],
    forbiddenAnswers: ['herd', 'cuddle', 'bamboozle'],
  },
  {
    id: 'b4-otters-raft',
    category: 'Animals',
    difficulty: 'hard',
    prompt: 'A group of sea otters floating together, sometimes holding paws so they don’t drift apart, is called a ___.',
    answer: 'raft',
    acceptableAnswers: ['raft of otters', 'raft of sea otters'],
    forbiddenAnswers: ['pod', 'float', 'huddle'],
  },

  // --- Surprising animal biology ---
  {
    id: 'b4-mantis-punch',
    category: 'Animals',
    difficulty: 'hard',
    prompt: 'The mantis shrimp punches so fast that the surrounding water briefly does this: ___.',
    answer: 'boils',
    acceptableAnswers: ['boil', 'it boils', 'boils the water'],
    forbiddenAnswers: ['freezes', 'glows', 'evaporates'],
  },
  {
    id: 'b4-mantis-eyes',
    category: 'Animals',
    difficulty: 'hard',
    prompt: 'Humans have three types of color-detecting cone in the eye; the mantis shrimp has roughly this many: ___.',
    answer: '16',
    acceptableAnswers: ['sixteen', '16 types'],
    forbiddenAnswers: ['3', '7', 'a million'],
  },
  {
    id: 'b4-starfish-brain',
    category: 'Animals',
    difficulty: 'medium',
    prompt: 'A starfish gets around and even hunts despite having no ___ at all.',
    answer: 'brain',
    acceptableAnswers: ['brains'],
    forbiddenAnswers: ['eyes', 'bones', 'blood'],
  },
  {
    id: 'b4-snail-sleep',
    category: 'Animals',
    difficulty: 'hard',
    prompt: 'In harsh, dry conditions some land snails can survive in a dormant, sealed-up state for as long as ___ years.',
    answer: 'three',
    acceptableAnswers: ['3', 'three years', '3 years'],
    forbiddenAnswers: ['one', 'a hundred', 'ten'],
  },
  {
    id: 'b4-wombat-poop',
    category: 'Animals',
    difficulty: 'hard',
    prompt: 'The wombat is the only known animal that produces droppings in this geometric shape: ___.',
    answer: 'cube',
    acceptableAnswers: ['cubes', 'cube-shaped', 'square'],
    forbiddenAnswers: ['round', 'star', 'triangle'],
  },
  {
    id: 'b4-octopus-walk',
    category: 'Animals',
    difficulty: 'hard',
    prompt: 'Some octopuses can stroll along the seabed on just this many of their eight arms: ___.',
    answer: 'two',
    acceptableAnswers: ['2', 'two arms'],
    forbiddenAnswers: ['eight', 'four', 'all of them'],
  },
  {
    id: 'b4-flamingo-grey',
    category: 'Animals',
    difficulty: 'medium',
    prompt: 'Flamingos aren’t born pink. Their chicks hatch out this color and only turn pink later from their diet: ___.',
    answer: 'grey',
    acceptableAnswers: ['gray', 'grey/white', 'grey or white', 'white'],
    forbiddenAnswers: ['pink', 'red', 'green'],
  },
  {
    id: 'b4-hummingbird-back',
    category: 'Animals',
    difficulty: 'medium',
    prompt: 'Hummingbirds are the only birds that can reliably fly in this direction: ___.',
    answer: 'backwards',
    acceptableAnswers: ['backward', 'in reverse'],
    forbiddenAnswers: ['forwards', 'upside down', 'up'],
  },
  {
    id: 'b4-tarantula-hairs',
    category: 'Animals',
    difficulty: 'hard',
    prompt: 'Threatened by a predator, many tarantulas defend themselves by flicking off clouds of irritating ___.',
    answer: 'hairs',
    acceptableAnswers: ['hair', 'bristles'],
    forbiddenAnswers: ['venom', 'webs', 'legs'],
  },

  // --- Words / names of baby & body things ---
  {
    id: 'b4-porcupette',
    category: 'Language',
    difficulty: 'hard',
    prompt: 'A baby porcupine has an especially cute name: it’s called a ___.',
    answer: 'porcupette',
    acceptableAnswers: [],
    forbiddenAnswers: ['pup', 'kit', 'cub'],
  },

  // --- Human body ---
  {
    id: 'b4-masseter',
    category: 'Human Body',
    difficulty: 'hard',
    prompt: 'By the force it can exert for its size, the strongest muscle in the human body is the chewing muscle in the ___.',
    answer: 'jaw',
    acceptableAnswers: ['masseter', 'the jaw'],
    forbiddenAnswers: ['heart', 'tongue', 'leg'],
  },
  {
    id: 'b4-femur',
    category: 'Human Body',
    difficulty: 'medium',
    prompt: 'The longest and strongest bone in the human body is the thigh bone, also known as the ___.',
    answer: 'femur',
    acceptableAnswers: [],
    forbiddenAnswers: ['tibia', 'spine', 'skull'],
  },
  {
    id: 'b4-taste-buds',
    category: 'Human Body',
    difficulty: 'hard',
    prompt: 'Your taste buds wear out and get completely replaced roughly every two ___.',
    answer: 'weeks',
    acceptableAnswers: ['week'],
    forbiddenAnswers: ['years', 'days', 'months'],
  },

  // --- Nature / plants / food ---
  {
    id: 'b4-banana-berry',
    category: 'Food',
    difficulty: 'hard',
    prompt: 'Botanically, a banana actually qualifies as a ___, while a strawberry does not.',
    answer: 'berry',
    acceptableAnswers: ['true berry'],
    forbiddenAnswers: ['fruit', 'vegetable', 'nut'],
  },
  {
    id: 'b4-cashew-ivy',
    category: 'Food',
    difficulty: 'hard',
    prompt: 'Cashews must be carefully processed before eating because the tree is in the same plant family as poison ___.',
    answer: 'ivy',
    acceptableAnswers: ['poison ivy'],
    forbiddenAnswers: ['oak', 'apple', 'mushroom'],
  },

  // --- Word origins ---
  {
    id: 'b4-salary-salt',
    category: 'Language',
    difficulty: 'hard',
    prompt: 'The English word "salary" traces back to the Latin word for ___, once tied to soldiers’ pay.',
    answer: 'salt',
    acceptableAnswers: ['sal'],
    forbiddenAnswers: ['money', 'silver', 'gold'],
  },
  {
    id: 'b4-quarantine',
    category: 'Language',
    difficulty: 'hard',
    prompt: 'The word "quarantine" comes from an Italian phrase meaning this many days, the time ships once waited out a plague: ___.',
    answer: 'forty',
    acceptableAnswers: ['40', 'forty days', '40 days'],
    forbiddenAnswers: ['seven', 'thirty', 'one hundred'],
  },
  {
    id: 'b4-muscle-mouse',
    category: 'Language',
    difficulty: 'hard',
    prompt: 'The word "muscle" comes from a Latin word that literally means "little ___": a flexing bicep looked like one moving under the skin.',
    answer: 'mouse',
    acceptableAnswers: ['little mouse', 'mouse (musculus)'],
    forbiddenAnswers: ['man', 'rope', 'hill'],
  },
  {
    id: 'b4-coulrophobia',
    category: 'Language',
    difficulty: 'hard',
    prompt: 'The tongue-twisting clinical name for the fear of clowns is ___.',
    answer: 'coulrophobia',
    acceptableAnswers: [],
    forbiddenAnswers: ['clownophobia', 'arachnophobia', 'claustrophobia'],
  },
]
